### ISSUE TITLE
Top 20px-30px of the screen are cut off, behind the title bar

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/openfl#1686]
Ok, this is a super weird issue, and I barely know where to start. Googling has gotten me nowhere, so I'm just going to describe the issue and hope somebody else knows what's going on.

When I run games made with OpenFL on my laptop, the top 20 to 30 pixels of the screen are being displayed underneath the title bar. Here, as an example, is Papers Please:

![papersplease](https://user-images.githubusercontent.com/2874150/29914628-6268081a-8e78-11e7-95bd-ad657339e761.png)

![papersplease2](https://user-images.githubusercontent.com/2874150/29914630-66df54de-8e78-11e7-88ec-177de4f3e1aa.png)

This problem ONLY affects OpenFL applications (both with applications I've compiled myself, and openfl games I've tried). No other applications on my laptop are doing this.

I have a Dell XPS 15 laptop. It's got duel graphics cards - an intel integrated one, and an nvidia one. This has only started happening recently, and I suspect it's due to a graphics card update or windows update on this machine.

The problem only happens when I'm using the intel integrated card. It doesn't happen when I tell my computer to use the nvidia card instead (which isn't the default setting).

Here is a simple openfl app that demonstrates the problem on my laptop - this is just HelloWorld, displaying a simple test image: [bugreport.zip](https://github.com/openfl/openfl/files/1266439/bugreport.zip)

If I build this targeting flash, I get the following window:

![flash](https://user-images.githubusercontent.com/2874150/29914812-04b0f08c-8e79-11e7-9f13-c6c65a158dcc.png)

However, if I build this targetting windows, I get the following:

![native2-dpioff](https://user-images.githubusercontent.com/2874150/29914835-0fa046d2-8e79-11e7-9561-2c179d0bc9f0.png)

You might also notice that the screen appears slightly scaled, weirdly. It's as if the app is creating a window the correct size, but then scaling the screen vertically to fill an imagined window that includes the area under the title bar.

Additional info!
  - This happens regardless of my DPI settings. I've tried changing it to different values and disabling it completely, no change.
  - This also happens on starling applications.
  - It doesn't seem to be related to the latest version of openfl. I tried compiling that test application with 4.9.2, and got the same result.
 - The mouse cursor disappears, and is useable under the title bar! (i.e. it picks up click events)

If this is only affecting my laptop and nobody else, then great, I guess? But it seems unlikely that that's the case. Any ideas what's happening here?

**Comment by MSGhero** [comment]
I have the same laptop, but it only started happening after I installed VSE 2013 over 2010. I'm on OpenFL 3.6.1.

`borderless="true" resizable="false"` in one of the `<window>` tags in project.xml resolves it as far as I've tested it, but of course that may not be ideal.

**Comment by jgranick** [comment]
Perhaps a newer SDL might help with this, though if its a GPU driver bug, it seems tricky to track, like the GL context is being given the wrong dimensions

**Comment by TerryCavanagh** [comment]
@MSGhero Really good to have confirmation that this isn't just happening on my laptop! (However in my case at least, I'd been using VSE 2013 for quite a while before this started happening - so I still suspect a GPU driver or windows update!)

@jgranick Happy to help test anything that you thing might help track it down! On those two though:
 - Changing DPI scaling doesn't make a difference
 - This isn't happening with any other SDL apps I've tried on my computer, just OpenFL (Weird, I know) :(

**Comment by jgranick** [comment]
Does resizing the window or toggling fullscreen make a difference?

**Comment by TerryCavanagh** [comment]
Yes! It does something super interesting!

If I switch to fullscreen, the image displays in the top left hand corner, like you'd expect. There's no obvious scaling going on, but it's hard to be sure.

However, if I resize the screen vertically, though, something a little weird happens. If I make the window larger than the original canvas, I get a very slight stretching effect, with the test image shrinking vertically a tiny bit. It's hard to notice, but here's a side by side comparison:

![bigger](https://user-images.githubusercontent.com/2874150/30021944-4ba307e6-91a8-11e7-8415-549461c1ec45.png)

Far more noticeable is the opposite - if I shrink the window vertically, the test image actually expands:

![smaller](https://user-images.githubusercontent.com/2874150/30021995-7b03be5e-91a8-11e7-899b-88cb38bb0599.png)

(this is also happening with horizontal window resizing, weirdly)

So! I don't know what to read into that, but it's evidence of something not working the way it's supposed to...

**Comment by MSGhero** [comment]
@TerryCavanagh has this changed at all for you? It hasn't for me on 6.5.0/5.8.0

**Comment by TerryCavanagh** [comment]
I can confirm that, unforunately, this is still happening for me on the latest versions of openfl and lime (6.5.0 and 5.8.0).

On a tangent, however! There is an interesting work around in development thanks to a conversation on the openfl slack. This doesn't solve this particular weird issue, but does at least mean that it's not a problem for development.

Basically, you can tell an exe to always use the nvidia gpu instead of the intel one by exporting a certain global variable in the exe (NvOptimusEnablement). This solves the problem, as it doesn't happen with the nvidia gpu is being used.

The only problem is that doing this requires a change in hxcpp rather than lime or openfl. This is currently being looked at - you can see the hxcpp issue regarding this here: https://github.com/HaxeFoundation/hxcpp/issues/676

**Comment by MSGhero** [comment]
Oh neat. That confirms it had to be a driver or windows update we installed over the summer that caused this. I wonder if the other libs that go through hxcpp have this problem...

And I didn't know OpenFL had a Slack channel!

**Comment by TerryCavanagh** [comment]
A development! You can ask your computer to use nvidia gpu by default by doing something like this:

``` haxe
@:cppFileCode('
#if defined(HX_WINDOWS)
   extern "C" {
      _declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001;
      _declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
   }
   #endif
')
@:keep class HighPerformance { }

class Test
{
   public static function main() trace("hello");
}
```

(re slack channel: yes, openfl has a slack, and it's pretty active! I think you need to talk to @larsiusprime for access - or at least, that's how I got into it.)

**Comment by RblSb** [comment]
@MSGhero you can just check this http://openfl-slack-invite.herokuapp.com/

**Comment by jgranick** [comment]
Hey guys, I think this should be resolved now:

https://github.com/openfl/lime/commit/5fe0f6efbe27f2696c6544e43d15249369fd6742

**Comment by TerryCavanagh** [comment]
Woo! Thanks!

So you've got this on by default, then? I think that's a good call :)

(I guess it is worth noting that this still happens on intel gpus on the Dell XPS 15, but I doubt anyone will care now that that we can just use the nvidia gpu. Also, it seems this started happening after an intel/windows update, so it's very possible that it'll fix itself in a later update anyway.)

**Comment by TerryCavanagh** [comment]
Hey hey,

So I recently got Neko working on my framework, and the same thing happens there. Is there anything that can be added to lime that might cause this to fix to be applied to neko too?

**Comment by jgranick** [comment]
I think it has to be present in C++ binaries, but it might be possible to either patch Neko (and do a custom release) or to do a custom C++ wrapper that boots up Neko. I tried doing it at runtime from the Lime binary, but I think by that point it already is too late. Maybe it can work if it's done before the window exists, but I thought I tried that before

**Comment by TerryCavanagh** [comment]
A small Neko patch seems good to me! But I guess it's not a straightforward thing to update Neko at this point :P (It does seem that the Nv dword needs to be right at the top of the exe, so I dunno)

(aside: just acknowledging that this is a pretty minor thing, and that neko is of limited interest to most people, and I'm not that bothered if this is never fixed)

**Comment by MSGhero** [comment]
Now that cpp compiles don’t take like 30 mins after updating VSE, I’m also pretty unbothered by neko target not having the fix.
