### ISSUE TITLE
CanvasShape renderer bug [html5]

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/openfl#461]
I tried to use Nape with html5 and Nape ShapeDebuger draws this in Opera:
![brba1](https://cloud.githubusercontent.com/assets/9349164/5645470/60911c5a-96bb-11e4-8d68-a1e635699c72.gif)
and in Firefox I got ```IndexSizeError: Index or size is negative or greater than the allowed amount``` with link to there https://github.com/openfl/openfl/blob/master/openfl/_internal/renderer/canvas/CanvasShape.hx#L52
How it looks with custom renderer:
![brba2](https://cloud.githubusercontent.com/assets/9349164/5645507/d39b4b30-96bb-11e4-9116-58c0c9a325b8.gif)
I think problem not in Nape, because if I use custom renderer it looks like I want.

Sample here https://github.com/T1mL3arn/OpenFlCanvasShapeRenderBugDemo . First running simulation with custom renderer. After mouse click runs simulation with Nape debugger renderer.

Openfl 2.2.1

**Comment by jgranick** [comment]
Does this work differently with the latest versions?

**Comment by T1mL3arn** [comment]
I updated dev builds for both Lime and OpenFl right now, and sample works the same way.

**Comment by raould** [comment]
(Probably not directly related? But I am getting an "IndexSizeError: Index or size is negative or greater than the allowed amount" at lime_graphics_utils_ImageCanvasUtil.copyPixels(). I am trying to figure out which variable is considered bad, but haven't figured it out yet. I tried the same webapp on Firefox 39 and Chromium 43.0.2357.130, both on Ubuntu Linux 14.04 x86; OpenFL 3.1.2, Lime 2.4.8. With Chromium, all the graphics appear (it is a HaxePunk game). With FF, the background appears but the sprites do not. Oddly enough the stack trace shows it is trying to update the tilemap background, not a sprite, afacit.)

**Comment by ibilon** [comment]
@raould your error should be fixed in the current dev version of lime

**Comment by raould** [comment]
@ibilon thanks, I was now looking on OpenFL and saw other related things so I was removing it from here since I am not at all sure the root cause is the same as this issue here when I reconsider. I will try new Lime! Thanks.

**Comment by T1mL3arn** [comment]
The problem is actually with scrollRect property, But I could not fixed it :(

**Comment by ibilon** [comment]
Couldn't reproduce the original issue anymore,
if there's a problem with scrollRect we'll monitor it in one of the already opened issues.

**Comment by T1mL3arn** [comment]
I updated Nape, FF, Opera, dev Lime and dev OpenFl and checked - the problem is still there. With one little exception - FF now works like Opera, and demoscene moves up instead down.

**Comment by ibilon** [comment]
Sorry didn't realized there was two renderers, and indeed the non-custom one triggers a bug.

**Comment by jgranick** [comment]
The lines are a bit faint, but it does work now in the current releases
