### ISSUE TITLE
GL/Windows: Lower framerate in "next" than "legacy"

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#596]
So far I'm finding a lower framerate in "next" than in "legacy." Specifically in flixel.

Reproduction:

- Compile flixel's "mode" demo using "lime test windows -debug" (legacy)
- Compile flixel's "mode" demo using "lime test windows -debug -Dnext" (next)
- In both games, hit "~" or "\" to bring up debug overlay with FPS counter
- Find an unobstructed place and stand around for a few seconds, don't do much
- Note the FPS and compare

Expectations:

- Next should have the same FPS or higher than legacy

Reality:

- Next: ~42 FPS
- Legacy: ~58 FPS

I know this is for debug mode, but mode is not a very complicated game and we need next to be on par or better than legacy for a smooth transition. Hopefully there's some low-hanging fruit optimizations we can try.

Also, although the difference between 42/58 may not seem huge, I've noticed far worse (unmeasured, anectodal) differences in FPS between legacy/next in more complicated projects, particularly Defender's Quest.

This is one of my top priorities for the next transition, please let me know how I can be of any help as I am happy to support this.

**Comment by mrcdk** [comment]
The main problem here, without dismissing others, is that it's being compiled in `debug` mode. In `legacy` we have a thin haxe layer that is implemented on top of a c++ codebase, in `next` we have a haxe codebase implemented on top of a thin layer of c++ code. 
Why does this matter? Easy, when you compile haxe to cpp in debug mode there is a lot of overhead from the extra information the cpp target needs for debug purposes so, as the haxe code gets bigger, the final executable will be slower. 
Does it affect `release` mode? Yes, but is not that noticeable.
To give you an example. OpenFL's BunnyMark sample, using `Thilesheet` rendering, goes from a maximum of 3750 bunnies at 60fps in debug mode to ~72k in release mode (on my computer). And this example only fill a few arrays and calculate a bunch of positions. So as the project grow more complex it will have a bigger impact.
Add the whole flixel source to the mix and now you have more haxe to cpp code that has to have debug information in it.
Solutions? I'm not sure how will be able to solve this. @jgranick is working on a better implementation of typed arrays that hopefully alleviates the problem.

**Comment by larsiusprime** [comment]
Okay, I'll report back with actual FPS numbers from release mode to get more proper benchmarks.

**Comment by larsiusprime** [comment]
Legacy+Release (~59 FPS):

![mode_fps_legacy](https://cloud.githubusercontent.com/assets/739064/7123649/421d7e20-e1e9-11e4-8dba-ac01925920bd.png)

Next+Release ():

I can't actually measure the FPS because of a crash in the GL renderer with text fields :) 
You can find my custom fork of Mode here:
https://github.com/larsiusprime/flixel-demos/tree/dev/Platformers/Mode

**Comment by larsiusprime** [comment]
Dunno why, but I don't get that error again when I try compiling once more.

Anyways, Next+Release(~57 FPS):

![mode_fps_next](https://cloud.githubusercontent.com/assets/739064/7124675/8f024444-e1f0-11e4-8578-5c27aa89f0f2.png)

**Comment by larsiusprime** [comment]
Note that in my screenshots my homegrown FPS counter works like this:

Current FPS / Average FPS

I just grabbed [this](https://github.com/openfl/lime/commit/a16894571e93e3675f568dec04251c2bef11c1f0) commit for lime and rebuilt, here are the results:

Neko:
Next+Release is still pretty slow (30-34 FPS) compared to Legacy+Release (solid 60 FPS).

Windows:
Looks like Solid 60 for Windows Release+Next now.

![mode_fps_next2](https://cloud.githubusercontent.com/assets/739064/7125332/9ff532b6-e1f5-11e4-9a71-79e3cfb16b6e.png)

Even goes *above* 60 FPS sometimes on the counter... :P

**Comment by larsiusprime** [comment]
Dang, Josh, don't know what you just did, but here's Windows Next/Debug:

![mode_fps_next_debug](https://cloud.githubusercontent.com/assets/739064/7125429/4f716ed0-e1f6-11e4-89ec-19f64e4196ab.png)

Veeeery close to a solid 60 FPS.

So Neko is still pretty slow but that seems like a separate issue. Are we convinced this is good enough to close for now?

**Comment by larsiusprime** [comment]
Here's some bunnymarks with the latest everything from Git:

(Release mode)

1K bunnies
Legacy: 61/60 
Next: 59/60

5K bunnies:
Legacy/Release: 61/60
Next: 39/60

10K bunnies
Legacy/Release: 36/60
Next/Release: 20/60

So when pushed, Next isn't quite as fast as Legacy just yet, but it's holding on.

**Comment by mrcdk** [comment]
which bunnymark? the Flixel one or the openfl one? if it's the openfl one, which test? tilesheet or bitmap?

Neko will be always be slow for the same reason windows in debug mode is slow. In legacy it only called cpp functions, in next everything is haxe.

**Comment by larsiusprime** [comment]
Sorry, this is FlxBunnymark (which I believe uses tilesheet).

**Comment by larsiusprime** [comment]
10K bunnies in OpenFL's bunnymark.

61-68 FPS in release/Next.

Compiling now for release/Legacy, will post comparison soon.

**Comment by larsiusprime** [comment]
Umm....

10K bunnies, OpenFL bunnymark.

31 FPS in release/legacy.

What?

(I should note that the fancy green background does not render for me in next at all, maybe that's why its so much faster, I'm not sure if I have an issue in my graphics card driver as others can't repro this).

**Comment by larsiusprime** [comment]
Oh, in terms of "which" openfl bunnymark... whichever one pops out when you do "lime test windows" rom the root project directory of openfl-samples/BunnyMark on a fresh git pull.

**Comment by jgranick** [comment]
Yeah, let's use the OpenFL BunnyMark, as it performs a lot better, and helps reduce the number of things we're testing :smile:

**Comment by larsiusprime** [comment]
Okey dokey, using the super latest stuff from git, including Josh's latest commit to lime with even more improvements, here are results:

OpenFL Bunnymark, whatever test (I assume tilesheet?) comes out of "lime test windows" from the root.

```
Version         FPS         Bunnies 
Legacy          31             500
Legacy          31            1000
Legacy          31             3000
Legacy          31             5000
Legacy          31             7500
Legacy          31            10000
Legacy          31            15000
Legacy          31            20000
Legacy          31            30000
Legacy          31            40000
Legacy          31            50000
Legacy          30            70000
Legacy          25            80000
Legacy          22            90000
Legacy          21          100000

Next         ~65             500
Next         ~65             1000
Next         ~65            3000
Next         ~65            5000
Next        ~65             7500
Next        ~65            10000
Next          62            15000
Next          61            20000
Next        ~53            30000
Next        ~44            40000
Next        ~34            50000
Next        ~27            70000
Next        ~22            80000
Next        ~21            90000
Next          19           100000
```

That said there are rendering discrepancies on my machine.

1. In next, there is no green background. @mrcdk has discussed this with me before, it happens on my machine but not on his. I suspect maybe it's a weird driver issue related to drawtiles, perhaps ANGLE support or something might fix it?
2. In next, the bunnies are purple! Perhaps an ARGB vs RGBA swizzle error?

**Comment by mrcdk** [comment]
Yeah, some recent change in lime made the bunnies purple :confused:

**Comment by jgranick** [comment]
The color problem has been fixed :smile:

**Comment by larsiusprime** [comment]
Confirmed: everything's the right color now. Still don't get the fancy green background but that's another issue.

**Comment by larsiusprime** [comment]
I'll close this for now. We can continue to optimize but the big discrepancy is gone now.

**Comment by larsiusprime** [comment]
Wow the latest commits are even better!

Mode gets higher framerate in next now than legacy (in cpp). Neko-next is definitely usable again, about half the framerate of CPP.
