### ISSUE TITLE
Mouse wheel / middle / right mouse events broken on native + legacy

### ISSUE THREAD

**Issue by Gama11** [openfl/openfl#722]
```haxe
package;

import openfl.display.Sprite;
import openfl.events.MouseEvent;

class Main extends Sprite {
	
	public function new () {
		super();
		
		openfl.Lib.current.stage.addEventListener(MouseEvent.MOUSE_WHEEL, function (e) {
			trace(e.delta);
		});
	}
}
```

This works fine (outputs -1 and 1 when scrolling) with next. With legacy however, there's no output.

I know that this used to work a while back, but I don't have an exact version.

Tested on neko and cpp with lime 2.4.4 and openfl 3.1.0. HTML5 doesn't seem to be affected and works with both next and legacy.

**Comment by Gama11** [comment]
It seems like this extends to middle and right mouse events as well:

```haxe
openfl.Lib.current.stage.addEventListener(MouseEvent.MIDDLE_MOUSE_DOWN, function (e) {
	trace("middle mouse down");
});

openfl.Lib.current.stage.addEventListener(MouseEvent.RIGHT_MOUSE_DOWN, function (e) {
	trace("right mouse down");
});
```

**Comment by OpmSaitama** [comment]
fix when ?

**Comment by Gama11** [comment]
Possible the same issue - middle and right mouse clicks fire left mouse events instead.

@OpmSaitama Might already have been fixed by this Lime commit: https://github.com/openfl/lime/commit/d1a27b7ee18cd149c3cd48cd2a53ade1c915c9fd

**Comment by jcward** [comment]
I'm using the latest OpenFL 3.1.1. and Lime 2.4.7 (which has the fix above, I believe) and I still don't get wheel events in legacy cpp. They show up has mousedown events. e.g.

    this.addEventListener(MouseEvent.MOUSE_WHEEL, function(e) { trace('wheel'); });
    this.addEventListener(MouseEvent.MOUSE_DOWN, function(e) { trace('down'); });

Traces `down` when I use the mouse wheel.

**Comment by brutalexcess** [comment]
http://prntscr.com/7qbbyb

I got it working using OpenFL 3.1.1 by attaching the event to the stage, not a Sprite.

Here is my code:

    addEventListener(Event.ADDED_TO_STAGE, init);
    }
    private function init(e:Event):Void
    {
        stage.addEventListener(MouseEvent.MOUSE_WHEEL, function(e) { trace("wheel"); } );
        stage.addEventListener(MouseEvent.MOUSE_DOWN, function(e) { trace("down"); } );
    }

I believe some events are triggered on a Sprite when that Sprite is active on the display list. If it's not the currently focused member, then you run into problems. Although I could be wrong.

**Comment by jgranick** [comment]
Fixed in https://github.com/openfl/lime/commit/6d107b6517318e34d7c82dd57610f7e7724a8fe6 :smile:
